name: CloudCannon Documentation
version: 3.0.3
url: https://docs.cloudcannon.com
future: true

author:
  name: CloudCannon
  email: support@cloudcannon.com

baseurl: /blog

builds:
  - Any
  - Static
  - Jekyll

plans:
  - Free
  - Basic
  - Pro

hostings:
  - Any
  - CloudCannon

collections:
  overview:
    title: Overview
    permalink: /overview/:title/
    active_prefix: overview
    output: true
    order: 1
  workflow:
    title: Workflow
    permalink: /workflow/:title/
    active_prefix: workflow
    output: true
    order: 2

defaults:
- scope:
    path: ""
  values:
    layout: docs
